remote_theme: "jekyll/minima@1e8a445"
title: Future Proof
description: My attempt at creating a blog

author:
  name: Jean Carlos
  email: "jeancarlosmachado@protonmail.com"

header_pages:
  - contact.md
  - about.md

minima:
  social_links:
    - title: My GitHub
      icon: github
      url: "https://github.com/caje-vi"
    - title: My LinkedIn
      icon: linkedin
      url: "https://linkedin.com/in/jean-vmachado"
  skin: solarized-dark

  plugins: 
    - jekyll-feed